name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          sudo apt-get install -y sshpass
      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 11319 root@0.tcp.ap.ngrok.io "
            kill-port --port 8080 &&
            cd library-api &&
            git pull origin main &&
            composer install &&
            php spark migrate &&
            nohup php spark serve > /dev/null 2>&1 &   # Jalankan di background
            echo 'Server running in the background.'"
      - name: Post Checkout code
        run: echo "Deployment completed successfully!"
